### ISSUE TITLE
Disable screen off timeout

### ISSUE THREAD

**Issue by BlueArcherX** [Terence-D/GamingInterfaceClientAndroid#325]
I kind of feel like maybe I just missed it in the settings somewhere, because it kinda makes things unusable, but I think this app should keep the screen turned on when it is open (like YouTube, etc), but my display still times out, forcing me to unlock it every time I need to press something.

Did I miss it somewhere?

**Comment by Terence-D** [comment]
That's odd. Mine stays on and I was thinking of adding a feature to turn that off. Bit busy with family but I'll investigate this further. What android version / device type? Get Outlook for Android

**Comment by BlueArcherX** [comment]
Samsung Galaxy S21+ (SM-G996U) with Android 12 / Security Patch level Nov 1, 2021

**Comment by Terence-D** [comment]
Perfect info.  I think I know how to fix this, I'll put out a small update to resolve this in a few days.

**Comment by Terence-D** [comment]
Code is building now, will be released to open beta tonight (can sign up via google play if interested), and live a few days after.  Closing the issue but if you still have issues please advise and I'll look into it.

Go into Menu -> Options -> set "Keep Screen On: to enabled.

Happy New Years

**Comment by BlueArcherX** [comment]
Just got back from a mini vacation, I'll check it out this week.

Thanks!
