### ISSUE TITLE
Can't Import Custom Button Images. Only Custom Background Images work 

### ISSUE THREAD

**Issue by doerek** [Terence-D/GamingInterfaceClientAndroid#82]
I installed the App Fresh on my smartphone,
But in the Editor I can't import my own icons.

I tap on Import -> select the file -> Save the button, but nothing happens.

Is there a specific File Format your App uses/needs?
I'm using *.PNG Files

**Comment by Terence-D** [comment]
Confirming I'm having the problem too. Will work on fixing this asap.

**Comment by Terence-D** [comment]
Fixed in branch 3.01, will be uploading it to GPlay and Amazon tomorrow after further testing / sleep :)
