### ISSUE TITLE
Unable to Connect - Client is not using the port it should use. (According to popup Error Message)

### ISSUE THREAD

**Issue by doerek** [Terence-D/GamingInterfaceClientAndroid#85]
Hello,

I installed the Server app on Win10 and granted it's changes to the Windows Firewall at first Start.
When i try to Connect using the App on my smartphone (while on the same Network) i get a popup Message with the following Content:

failed to connect to /192.168.1.2 (port 8091) from /192.168.45 (port 41194)

Of course, the Port in the Android App is set to the same value (8091)
I`m using a 1+ 6T with Android 9 installed.

The Port wich gets used seems to chang every time i tap "start"

![Screenshot_20190628-172959](https://user-images.githubusercontent.com/2093684/60355357-7662a600-99ce-11e9-84a5-a726eac2db69.jpg)

**Comment by Terence-D** [comment]
Hi there, you need to make sure that your computer the android device is connecting to has that 192.168.1.2 address (i'm assuming your android is 192.168.1.45)  

if you are using the default Windows software, try this guide for the firewall port opening:
https://www.tomshardware.com/news/how-to-open-firewall-ports-in-windows-10,36451.html

**Comment by doerek** [comment]
Is it normal that the port that get used is a different one than the one I set in the settings? Or does the error message at the bottom just show the wrong port number.

In the screenshot you can see that the both ports differentiate.

**Comment by doerek** [comment]
**Problem Solved.** Besides the Rule that gets created at first start, you need to deactivate "Windows Defender Firewall" for your Local Network.

**Comment by Terence-D** [comment]
you shouldn't have to deactivate the Windows Defender firewall.  it will work, but i highly discourage that as it opens you up to other risks.  I am using it with Windows Defender and i'm not having any problems.

**Comment by doerek** [comment]
If I keep the WDF for local network  active the Android App always uses a different port no matter wich rule I set in the firewall settings. Really strange behavior...

**Comment by Terence-D** [comment]
that port that you are seeing is probably the port its sending on, it's not the active port.  the port isn't changing due to the firewall being on or off.  Ensure you've added Gaming Interface Client an exception in your firewall rules.
